### ISSUE TITLE
Select Site only showing Internal - No external options

### ISSUE THREAD

**Issue by jjshortbread** [SalesforceLabs/survey-force#152]
After successfully testing in my dev org last couple of weeks, I installed SurveyForce in my preprod org for testing. 

I've done everything but for the sharing options, I only get Internal under Select Site

Even when I have selected Email Link w / Contact Merge , I am not getting any options to select any of my active sites. 

Any ideas? Thank you

**Comment by jjshortbread** [comment]
@jrattanpal Will really appreciate any input as had a project going live next week :(

**Comment by jrattanpal** [comment]
This is because of Enhanced Domains. If you have deployed enhanced domain
on that org then the old code doesn't work.

I have made a change. This works with or without enhanced domains. I have
also published this change on APpExchange in latest version.

Change is in
https://github.com/SalesforceLabs/survey-force/blob/main/force-app/main/default/classes/ViewShareSurveyComponentController.cls

Change is at line#59 and #75. You can manually change the code in that
class and it will work.

https://github.com/SalesforceLabs/survey-force/commit/636ced70b938cf264eeed01ecd6b448c19979eb5

You can get the code and make this change manually (it's very small). It
should work for you.

**Comment by jjshortbread** [comment]
you are a legend bro @jrattanpal will give it a shot and report back. Thank you

**Comment by jjshortbread** [comment]
It worked thank you @jrattanpal . 

Absolute legend! thanks once again
