### ISSUE TITLE
Limitation of only 4 options on single select question?

### ISSUE THREAD

**Issue by Tek-Tom** [SalesforceLabs/survey-force#36]
Is this a limitation of Surveyforce? Can I only add 4 options in any single select question? Also you don't have a simple branching feature? If they answer yes to one question you can't ask them why they said yes or no if they chose no? That is a necessary feature of any survey software, this is so low featured it's almost useless...

**Comment by claico** [comment]
Surveyforce never implementing branching. There was an attempt to add it several years ago, but it is complicated, especially when you start back-tracking. Still the code is open source, so it can be modified.

The new Salesforce Surveys (native surveys as part of salesforce.com) went GA in Spring 18. In the Summer 18 release, it added conditional branching. Salesforce Surveys requires a "creator" license to create new surveys, and you have to have Communities if you want to expose it to the public (Surveyforce works with Sites). The creator license is free with Health Cloud, but $75 per license per month otherwise. It allows unlimited surveys and unlimited responses (subject to other limitations like data from records (like a record for every question response), visits to your community site, etc.) But ALL editions of salesforce.com have the ability to create and use ONE (and only one) survey without paying for the creator license.

In the Trailblazer community, I created a [Salesforce Surveys collaboration group](https://success.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F93A0000004hf1). It is a good place to start if you want to try it.

This link is a live survey that has conditional branching - https://tccsummer18-developer-edition.gus.force.com/survey/runtimeApp.app?invitationId=0KiB0000000Cjzc&surveyName=summer_18_demonstration&UUID=3ba2ff8c-affb-473e-a682-69de727f3d64
