### ISSUE TITLE
Object names (labels) for Survey Force

### ISSUE THREAD

**Issue by charles-thompson-salesforce-com** [SalesforceLabs/survey-force#42]
@jrattanpal - thank you so much for your interest in maintaining Survey Force.

You're probably aware that Salesforce Surveys is a commercial product that provides more capability for Surveys than Survey Force, but it costs quite a lot for a large number of responses.  For many of us, Survey Force does the job and it's open source!

But there's an issue.  Both Salesforce Surveys and Survey Force use similar names for objects.  Would it be possible in a future release to include "SF" (or a similar abbreviation) in the names of all Survey Force custom objects so we can differentiate them more easily?

**Comment by jrattanpal** [comment]
While it's an easy thing to do, I hesitate to  do so because of existing customizations. 

Survey Force is open source and unmanaged package. Which means customers have built customizations on top of it. When I release any fixes, customers may copy the code for use and modify it for their existing customizations.

**Comment by charles-thompson-salesforce-com** [comment]
Sure, I understand.  I may try customising the names myself then.
Regards,
- Charles
