### ISSUE TITLE
Error:You have already taken this survey

### ISSUE THREAD

**Issue by friscoandy** [SalesforceLabs/survey-force#50]
We have noticed a strange issue that is only affecting some users. When they submit the survey, they see an error message saying that they have already taken the survey. It is not possible that they have already taken the survey because it is a brand new survey. I get this error when I test but another admin on my team does not get the error and is able to submit. Have you seen this before?
![error](https://user-images.githubusercontent.com/55755308/71847650-09258100-3093-11ea-80b6-1796ceb1eeea.png)

**Comment by jrattanpal** [comment]
Code for this is at https://github.com/SalesforceLabs/survey-force/blob/master/src/classes/ViewSurveyController.cls

In function private Boolean AddSurveyTaker()

From line#377 - 388

This code has always been there but I recently fixed it. That's why you are facing this. This will only work for internal users but not anonymous users (as they all share same Guest User ID so we can't do it there).

You can remove that code if you want or change the criteria to match your needs

**Comment by friscoandy** [comment]
We will give this a try. You are the best!
